### ISSUE TITLE
Random crash shift-clicking items into a chest

### ISSUE THREAD

**Issue by xeronut** [Tonius/Zoom#1]
Hello!  I'm not entirely sure if this crash is the fault of Zoom as it happens without the Zoom key pressed (mine is set to Mouse4) but it's listed in the log, so I figured this would be a good place to start.

http://pastebin.com/S8UewUw2

Sometimes I shift-click items into a chest and get this crash.  I've done it three times now, and it happens as I shift-click every time.  Should I also post this on Botania's issue tracker (it's another mod listed in the log)?

**Comment by Tonius** [comment]
Should be fixed in [Zoom 1.0.1](http://minecraft.curseforge.com/projects/zoom/files/2264234)
